import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import type { ToolkitKind } from "./types";

// Entries under a toolkit folder that should never contribute to its hash.
// `node_modules/` and `bun.lock` are derivable from `package.json` and are
// regenerated by `bun install`, so excluding them keeps the hash stable
// across the untrust/trust/install lifecycle.
const FOLDER_EXCLUDE_DIRS = new Set<string>([
  "node_modules",
  ".git",
  ".DS_Store",
  "bun.lock",
  "bun.lockb",
]);

function sha256File(filepath: string): string {
  const h = crypto.createHash("sha256");
  h.update(fs.readFileSync(filepath));
  return h.digest("hex");
}

/** Recursively list all files under `root` (relative paths), skipping
 *  anything whose name matches an exclude entry at any depth. */
function listFilesRelative(root: string): string[] {
  const out: string[] = [];
  function walk(currentRel: string): void {
    const abs = path.join(root, currentRel);
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const ent of entries) {
      if (FOLDER_EXCLUDE_DIRS.has(ent.name)) continue;
      const relChild = currentRel ? path.posix.join(currentRel, ent.name) : ent.name;
      if (ent.isSymbolicLink()) {
        // Ignore symlinks entirely - we never resolve them for hashing to
        // avoid being tricked into hashing something outside the folder.
        continue;
      }
      if (ent.isDirectory()) {
        walk(relChild);
      } else if (ent.isFile()) {
        out.push(relChild);
      }
    }
  }
  walk("");
  out.sort();
  return out;
}

/** Compute the canonical content hash for a toolkit.
 *
 *  - `file` kind: sha256 of the .ts bytes.
 *  - `folder` kind: sha256 of the sorted `<relPath>\0<sha256Hex>\n` list for
 *    every file under the folder, excluding `node_modules/` and `bun.lock`.
 */
export function computeContentHash(entryPath: string, kind: ToolkitKind): string {
  if (kind === "file") {
    return sha256File(entryPath);
  }
  const folder = path.dirname(entryPath);
  const files = listFilesRelative(folder);
  const agg = crypto.createHash("sha256");
  for (const rel of files) {
    const abs = path.join(folder, rel);
    let fileHash: string;
    try {
      fileHash = sha256File(abs);
    } catch {
      // File vanished mid-scan. Still incorporate its path so a race doesn't
      // collide with a legitimately-different state.
      fileHash = "missing";
    }
    agg.update(rel);
    agg.update("\0");
    agg.update(fileHash);
    agg.update("\n");
  }
  return agg.digest("hex");
}

/** Hash the text used to seed an embedding (description + triggers) so we
 *  can invalidate the cached vector when the toolkit is re-enabled with
 *  different text without repopulating unchanged rows. */
export function hashEmbeddingSource(description: string, triggers: string[]): string {
  const h = crypto.createHash("sha256");
  h.update(description);
  h.update("\u0001");
  for (const t of triggers) {
    h.update(t);
    h.update("\u0001");
  }
  return h.digest("hex");
}
