import type { SettingGroup } from "../types.ts";

export const appearanceGroup: SettingGroup = {
  id: "appearance",
  destination: "client",
  name: "Appearance",
  icon: "i-material-symbols-palette",
  iconInactive: "i-material-symbols-palette-outline",
  sections: [
    {
      label: "Layout",
      fields: [
        {
          id: "layout.monitor",
          name: "Monitor",
          description: "Which monitor the app opens on.",
          type: "select",
          optionsSource: "monitors",
          defaultValue: "primary",
          descriptionTier: "ondemand",
        },
        {
          id: "layout.alignment",
          name: "Window Alignment",
          description: "Where the window sits on the monitor.",
          type: "select",
          defaultValue: "center",
          options: [
            { value: "left", label: "Left" },
            { value: "center", label: "Center" },
            { value: "right", label: "Right" },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "layout.width",
          name: "Window Width",
          description: "Width of the app window.",
          type: "number",
          defaultValue: 700,
          suffix: "px",
          regex: [
            {
              regex: "^(?:4[0-9]{2}|[5-9][0-9]{2}|1[01][0-9]{2}|1200)$",
              errorMessage: "Must be between 400 and 1200",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.settings.sidebarCollapsed",
          name: "Collapse Settings Sidebar",
          description: "Shrink this sidebar to icons only.",
          type: "boolean",
          defaultValue: false,
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.settings.horizontalThreshold",
          name: "Side-by-Side Layout Width",
          description:
            "Above this window width, each setting shows its label and control on one row.",
          type: "number",
          defaultValue: 450,
          suffix: "px",
          descriptionTier: "ondemand",
          regex: [
            {
              regex: "^([4-9][0-9]{2}|[12][0-9]{3})$",
              errorMessage: "Must be between 400 and 2999",
            },
          ],
        },
      ],
    },
    {
      label: "Theme",
      fields: [
        {
          id: "appearance.theme",
          name: "Color Mode",
          description: "Light, dark, or match your system.",
          type: "select",
          defaultValue: "auto",
          options: [
            { value: "light", label: "Light" },
            { value: "dark", label: "Dark" },
            { value: "auto", label: "Auto (System)" },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.textSize",
          name: "Text Size",
          description: "Base text size across the app.",
          type: "number",
          defaultValue: 16,
          suffix: "px",
          regex: [
            {
              regex: "^(?:1[2-9]|2[0-9]|3[0-2])$",
              errorMessage: "Must be between 12 and 32",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.defaultFont",
          name: "Font",
          description: "The main font for the app. Default uses your system font.",
          type: "select",
          optionsSource: "fonts",
          defaultValue: "default",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.monoFont",
          name: "Code Font",
          description:
            "The font for code and command previews. Default uses your system monospace font.",
          type: "select",
          optionsSource: "fonts",
          defaultValue: "default",
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Bubbles",
      fields: [
        {
          id: "appearance.userBubbleColor",
          name: "Your Bubble Color",
          description: "Color of your chat message bubbles.",
          type: "color",
          defaultValue: "#86efacff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.agentBubbleColor",
          name: "Agent Bubble Color",
          description: "Color of the agent's chat message bubbles.",
          type: "color",
          defaultValue: "#93c5fdff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.secondaryAgentBubbleColor",
          name: "Secondary Agent Color",
          description: "Bubble color when a reply comes from your secondary model.",
          type: "color",
          defaultValue: "#d8b4feff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.bubbleShadowColor",
          name: "Shadow Color",
          description:
            "Color of the shadow around every bubble in the app. Set transparency to 0 to remove it.",
          type: "color",
          defaultValue: "#00000033",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.bubbleShadowDistance",
          name: "Shadow Size",
          description: "How far the shadow reaches out from each bubble's edge.",
          type: "number_slider",
          defaultValue: 8,
          min: 0,
          max: 40,
          step: 1,
          suffix: "px",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.bubbleBlurEnabled",
          name: "Blur Around Bubbles",
          description:
            "Blur the area around each bubble so it stands out from whatever is behind the window. Turn off for a plain drop shadow instead.",
          type: "boolean",
          defaultValue: true,
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.bubbleBlurRings",
          name: "Blur Smoothness",
          description: "Smoother blur, at a small performance cost.",
          type: "number_slider",
          defaultValue: 1,
          min: 1,
          max: 6,
          step: 1,
          editableWhen: { field: "appearance.bubbleBlurEnabled", eq: true },
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Theme Colors",
      fields: [
        {
          id: "appearance.defaultColor",
          name: "Base Color",
          description:
            "The neutral color everything is built from: backgrounds, borders, text. Near-gray for classic, a subtle tint to theme the whole app.",
          type: "color",
          lockedLightness: 0.985,
          defaultValue: "#737373ff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.systemMessageDefaultColor",
          name: "System Bubble Tint",
          description:
            "Give system bubbles (thinking, tool calls) their own base color. Transparent uses the base color.",
          type: "color",
          lockedLightness: 0.985,
          defaultValue: "#00000000",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.userInputDefaultColor",
          name: "Input Area Tint",
          description: "Give the input area its own base color. Transparent uses the base color.",
          type: "color",
          lockedLightness: 0.985,
          defaultValue: "#00000000",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.sessionBarDefaultColor",
          name: "Session Bar Tint",
          description: "Give the session bar its own base color. Transparent uses the base color.",
          type: "color",
          lockedLightness: 0.985,
          defaultValue: "#00000000",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.settingsDefaultColor",
          name: "Settings Tint",
          description:
            "Give the settings panel its own base color. Transparent uses the base color.",
          type: "color",
          lockedLightness: 0.985,
          defaultValue: "#00000000",
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Accent Colors",
      fields: [
        {
          id: "appearance.accentRed",
          name: "Red",
          description: "Used for errors and destructive actions.",
          type: "color",
          lockedLightness: 0.922,
          defaultValue: "#ef4444ff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.accentBlue",
          name: "Blue",
          description: "The main accent, used across the app.",
          type: "color",
          lockedLightness: 0.922,
          defaultValue: "#3b82f6ff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.accentPurple",
          name: "Purple",
          description: "An additional accent.",
          type: "color",
          lockedLightness: 0.922,
          defaultValue: "#a855f7ff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.accentGreen",
          name: "Green",
          description: "Used for success and confirmation.",
          type: "color",
          lockedLightness: 0.922,
          defaultValue: "#22c55eff",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.accentYellow",
          name: "Yellow",
          description: "Used for warnings and loading.",
          type: "color",
          lockedLightness: 0.922,
          defaultValue: "#eab308ff",
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Style",
      fields: [
        {
          id: "appearance.roundedSmall",
          name: "Small Corner Radius",
          description: "Rounding for small elements like code blocks.",
          type: "number_slider",
          defaultValue: 6,
          min: 0,
          max: 16,
          step: 1,
          suffix: "px",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.roundedMedium",
          name: "Medium Corner Radius",
          description: "Rounding for inputs and small cards.",
          type: "number_slider",
          defaultValue: 8,
          min: 0,
          max: 20,
          step: 1,
          suffix: "px",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.roundedLarge",
          name: "Large Corner Radius",
          description: "Rounding for bubbles, modals, and panels.",
          type: "number_slider",
          defaultValue: 16,
          min: 0,
          max: 32,
          step: 1,
          suffix: "px",
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.animationsEnabled",
          name: "Animations",
          description: "Animate message entry, transitions, and expanding sections.",
          type: "boolean",
          defaultValue: true,
          descriptionTier: "ondemand",
        },
        {
          id: "appearance.animationSpeedMultiplier",
          name: "Animation Speed",
          description: "How fast animations play.",
          type: "number_slider",
          defaultValue: 100,
          min: 25,
          max: 400,
          step: 25,
          suffix: "%",
          editableWhen: { field: "appearance.animationsEnabled", eq: true },
          descriptionTier: "ondemand",
        },
      ],
    },
  ],
};
