import type { SettingGroup } from "../types.ts";

export const ttsGroup: SettingGroup = {
  id: "tts",
  destination: "client",
  name: "Text-to-Speech",
  icon: "i-material-symbols-volume-up-rounded",
  iconInactive: "i-material-symbols-volume-up-outline-rounded",
  sections: [
    {
      fields: [
        {
          id: "tts.enabled",
          name: "Enable Text-to-Speech",
          description:
            "Read assistant responses aloud as they stream.\nKeeps the voice model loaded in memory while enabled and frees it on disable.",
          type: "boolean",
          defaultValue: false,
          descriptionTier: "ondemand",
        },
        {
          id: "tts.spellOutEmojis",
          name: "Spell Out Emojis",
          description:
            "Pass emojis through to the voice model so it pronounces them.\nWhen disabled (default), emojis are stripped before synthesis.",
          type: "boolean",
          defaultValue: false,
          visibleWhen: { field: "tts.enabled", eq: true },
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Voice",
      visibleWhen: { field: "tts.enabled", eq: true },
      fields: [
        {
          id: "tts.voice",
          name: "Voice",
          description:
            "Voice model used for speech synthesis.\nSelecting a voice downloads its file the first time it is used.",
          type: "select",
          defaultValue: "af_bella",
          descriptionTier: "ondemand",
          options: [
            { value: "af_alloy", label: "American • Female • Alloy" },
            { value: "af_aoede", label: "American • Female • Aoede" },
            { value: "af_bella", label: "American • Female • Bella" },
            { value: "af_heart", label: "American • Female • Heart" },
            { value: "af_jessica", label: "American • Female • Jessica" },
            { value: "af_kore", label: "American • Female • Kore" },
            { value: "af_nicole", label: "American • Female • Nicole" },
            { value: "af_nova", label: "American • Female • Nova" },
            { value: "af_river", label: "American • Female • River" },
            { value: "af_sarah", label: "American • Female • Sarah" },
            { value: "af_sky", label: "American • Female • Sky" },
            { value: "am_adam", label: "American • Male • Adam" },
            { value: "am_echo", label: "American • Male • Echo" },
            { value: "am_eric", label: "American • Male • Eric" },
            { value: "am_fenrir", label: "American • Male • Fenrir" },
            { value: "am_liam", label: "American • Male • Liam" },
            { value: "am_michael", label: "American • Male • Michael" },
            { value: "am_onyx", label: "American • Male • Onyx" },
            { value: "am_puck", label: "American • Male • Puck" },
            { value: "am_santa", label: "American • Male • Santa" },
            { value: "bf_alice", label: "British • Female • Alice" },
            { value: "bf_emma", label: "British • Female • Emma" },
            { value: "bf_isabella", label: "British • Female • Isabella" },
            { value: "bf_lily", label: "British • Female • Lily" },
            { value: "bm_daniel", label: "British • Male • Daniel" },
            { value: "bm_fable", label: "British • Male • Fable" },
            { value: "bm_george", label: "British • Male • George" },
            { value: "bm_lewis", label: "British • Male • Lewis" },
            { value: "jf_alpha", label: "Japanese • Female • Alpha" },
            { value: "jf_gongitsune", label: "Japanese • Female • Gongitsune" },
            { value: "jf_nezumi", label: "Japanese • Female • Nezumi" },
            { value: "jf_tebukuro", label: "Japanese • Female • Tebukuro" },
            { value: "jm_kumo", label: "Japanese • Male • Kumo" },
            { value: "zf_xiaobei", label: "Mandarin • Female • Xiaobei" },
            { value: "zf_xiaoni", label: "Mandarin • Female • Xiaoni" },
            { value: "zf_xiaoxiao", label: "Mandarin • Female • Xiaoxiao" },
            { value: "zf_xiaoyi", label: "Mandarin • Female • Xiaoyi" },
            { value: "zm_yunjian", label: "Mandarin • Male • Yunjian" },
            { value: "zm_yunxi", label: "Mandarin • Male • Yunxi" },
            { value: "zm_yunxia", label: "Mandarin • Male • Yunxia" },
            { value: "zm_yunyang", label: "Mandarin • Male • Yunyang" },
            { value: "ef_dora", label: "Spanish • Female • Dora" },
            { value: "em_alex", label: "Spanish • Male • Alex" },
            { value: "em_santa", label: "Spanish • Male • Santa" },
            { value: "ff_siwis", label: "French • Female • Siwis" },
            { value: "hf_alpha", label: "Hindi • Female • Alpha" },
            { value: "hf_beta", label: "Hindi • Female • Beta" },
            { value: "hm_omega", label: "Hindi • Male • Omega" },
            { value: "hm_psi", label: "Hindi • Male • Psi" },
            { value: "if_sara", label: "Italian • Female • Sara" },
            { value: "im_nicola", label: "Italian • Male • Nicola" },
            { value: "pf_dora", label: "Brazilian Portuguese • Female • Dora" },
            { value: "pm_alex", label: "Brazilian Portuguese • Male • Alex" },
            { value: "pm_santa", label: "Brazilian Portuguese • Male • Santa" },
          ],
        },
        {
          id: "tts.minChunkWords",
          name: "Min Words Per Chunk",
          description:
            "Smallest number of words to buffer before sending a chunk to the voice model.\nHigher values produce smoother prosody at the cost of latency.",
          type: "number",
          defaultValue: 8,
          suffix: "words",
          regex: [{
            regex: "^[1-9][0-9]*$",
            errorMessage: "Must be a positive integer",
          }],
          advanced: true,
          descriptionTier: "ondemand",
        },
        {
          id: "tts.synthesisSpeed",
          name: "Speech Synthesis Speed",
          description:
            "Speed the voice model is asked to render speech at.\nAffects the prosody of the generated audio (lower = more relaxed pacing, higher = more clipped).\nAccepted range: 0.25 to 3.",
          type: "float",
          defaultValue: 1,
          suffix: "x",
          regex: [
            {
              regex: "^(0\\.(2[5-9]|[3-9]\\d?)|[12](\\.\\d+)?|3(\\.0+)?)$",
              errorMessage: "Must be between 0.25 and 3",
            },
          ],
          advanced: true,
          descriptionTier: "ondemand",
        },
        {
          id: "tts.playbackSpeed",
          name: "Playback Speed",
          description:
            "Speed the synthesized audio is replayed at.\nApplied after synthesis, so pitch scales with the multiplier (higher = higher-pitched voice).\nAccepted range: 0.25 to 3.",
          type: "float",
          defaultValue: 1,
          suffix: "x",
          regex: [
            {
              regex: "^(0\\.(2[5-9]|[3-9]\\d?)|[12](\\.\\d+)?|3(\\.0+)?)$",
              errorMessage: "Must be between 0.25 and 3",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "tts.volume",
          name: "Volume",
          description:
            "Playback volume for synthesized speech.\nAccepted range: 0 to 100.",
          type: "number_slider",
          defaultValue: 70,
          min: 0,
          max: 100,
          step: 1,
          suffix: "%",
          descriptionTier: "none",
        },
      ],
    },
  ],
};
