// Text-to-Speech: one hybrid group spanning client and core. The enable
// toggle lives on the core because the synthesis engine does: core computes
// the Kokoro files into its required-downloads snapshot from `tts.enabled`,
// so a client-side value would leave requirements (and the pending-downloads
// gate) blind to it. Playback and batching settings stay on the client.

import type { SettingGroup } from "../types.ts";

export const ttsGroup: SettingGroup = {
  id: "tts",
  destination: ["client", "core"],
  name: "Text-to-Speech",
  description:
    "Have the agent read its replies aloud. Playback runs on this device; the speech model runs on the core.",
  descriptionTier: "ondemand",
  icon: "i-material-symbols-volume-up-rounded",
  iconInactive: "i-material-symbols-volume-up-outline-rounded",
  sections: [
    {
      label: "General",
      destination: "core",
      fields: [
        {
          id: "tts.enabled",
          name: "Enable Text-to-Speech",
          description: "Read the agent's replies aloud as they arrive.",
          type: "boolean",
          defaultValue: false,
          descriptionTier: "ondemand",
        },
      ],
    },
    {
      label: "Voice",
      destination: "client",
      visibleWhen: { field: "tts.enabled", eq: true },
      fields: [
        {
          id: "tts.spellOutEmojis",
          name: "Read Emojis Aloud",
          description: "Pronounce emojis instead of skipping them.",
          type: "boolean",
          defaultValue: false,
          descriptionTier: "ondemand",
        },
        {
          id: "tts.voice",
          name: "Voice",
          description: "The voice used to read replies. Downloads the first time you use it.",
          type: "select",
          defaultValue: "af_bella",
          descriptionTier: "ondemand",
          options: [
            { value: "af_alloy", label: "American • Female • Alloy" },
            { value: "af_aoede", label: "American • Female • Aoede" },
            { value: "af_bella", label: "American • Female • Bella" },
            { value: "af_heart", label: "American • Female • Heart" },
            { value: "af_jessica", label: "American • Female • Jessica" },
            { value: "af_kore", label: "American • Female • Kore" },
            { value: "af_nicole", label: "American • Female • Nicole" },
            { value: "af_nova", label: "American • Female • Nova" },
            { value: "af_river", label: "American • Female • River" },
            { value: "af_sarah", label: "American • Female • Sarah" },
            { value: "af_sky", label: "American • Female • Sky" },
            { value: "am_adam", label: "American • Male • Adam" },
            { value: "am_echo", label: "American • Male • Echo" },
            { value: "am_eric", label: "American • Male • Eric" },
            { value: "am_fenrir", label: "American • Male • Fenrir" },
            { value: "am_liam", label: "American • Male • Liam" },
            { value: "am_michael", label: "American • Male • Michael" },
            { value: "am_onyx", label: "American • Male • Onyx" },
            { value: "am_puck", label: "American • Male • Puck" },
            { value: "am_santa", label: "American • Male • Santa" },
            { value: "bf_alice", label: "British • Female • Alice" },
            { value: "bf_emma", label: "British • Female • Emma" },
            { value: "bf_isabella", label: "British • Female • Isabella" },
            { value: "bf_lily", label: "British • Female • Lily" },
            { value: "bm_daniel", label: "British • Male • Daniel" },
            { value: "bm_fable", label: "British • Male • Fable" },
            { value: "bm_george", label: "British • Male • George" },
            { value: "bm_lewis", label: "British • Male • Lewis" },
            { value: "jf_alpha", label: "Japanese • Female • Alpha" },
            { value: "jf_gongitsune", label: "Japanese • Female • Gongitsune" },
            { value: "jf_nezumi", label: "Japanese • Female • Nezumi" },
            { value: "jf_tebukuro", label: "Japanese • Female • Tebukuro" },
            { value: "jm_kumo", label: "Japanese • Male • Kumo" },
            { value: "zf_xiaobei", label: "Mandarin • Female • Xiaobei" },
            { value: "zf_xiaoni", label: "Mandarin • Female • Xiaoni" },
            { value: "zf_xiaoxiao", label: "Mandarin • Female • Xiaoxiao" },
            { value: "zf_xiaoyi", label: "Mandarin • Female • Xiaoyi" },
            { value: "zm_yunjian", label: "Mandarin • Male • Yunjian" },
            { value: "zm_yunxi", label: "Mandarin • Male • Yunxi" },
            { value: "zm_yunxia", label: "Mandarin • Male • Yunxia" },
            { value: "zm_yunyang", label: "Mandarin • Male • Yunyang" },
            { value: "ef_dora", label: "Spanish • Female • Dora" },
            { value: "em_alex", label: "Spanish • Male • Alex" },
            { value: "ff_siwis", label: "French • Female • Siwis" },
            { value: "hf_alpha", label: "Hindi • Female • Alpha" },
            { value: "hf_beta", label: "Hindi • Female • Beta" },
            { value: "hm_omega", label: "Hindi • Male • Omega" },
            { value: "hm_psi", label: "Hindi • Male • Psi" },
            { value: "if_sara", label: "Italian • Female • Sara" },
            { value: "im_nicola", label: "Italian • Male • Nicola" },
            { value: "pf_dora", label: "Brazilian Portuguese • Female • Dora" },
            { value: "pm_alex", label: "Brazilian Portuguese • Male • Alex" },
            { value: "pm_santa", label: "Brazilian Portuguese • Male • Santa" },
          ],
        },
        {
          id: "tts.minChunkWords",
          name: "Words Per Chunk",
          description:
            "How many words to gather before speaking. Higher sounds smoother but starts later.",
          type: "number",
          defaultValue: 8,
          suffix: "words",
          regex: [
            {
              regex: "^[1-9][0-9]*$",
              errorMessage: "Must be a positive integer",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "tts.synthesisSpeed",
          name: "Synthesis Speed",
          description: "How fast the voice is generated. Affects pacing.",
          type: "float",
          defaultValue: 1,
          suffix: "x",
          regex: [
            {
              regex: "^(0\\.(2[5-9]|[3-9]\\d?)|[12](\\.\\d+)?|3(\\.0+)?)$",
              errorMessage: "Must be between 0.25 and 3",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "tts.playbackSpeed",
          name: "Playback Speed",
          description: "How fast the audio plays back. Also shifts pitch.",
          type: "float",
          defaultValue: 1,
          suffix: "x",
          regex: [
            {
              regex: "^(0\\.(2[5-9]|[3-9]\\d?)|[12](\\.\\d+)?|3(\\.0+)?)$",
              errorMessage: "Must be between 0.25 and 3",
            },
          ],
          descriptionTier: "ondemand",
        },
        {
          id: "tts.volume",
          name: "Volume",
          description: "Playback volume.",
          type: "number_slider",
          defaultValue: 70,
          min: 0,
          max: 100,
          step: 1,
          suffix: "%",
          descriptionTier: "ondemand",
        },
      ],
    },
  ],
};
