// Ed25519 public keys for verifying signed manifests from the Tomat CDN.
//
// AUTO-GENERATED by `deno task website:deploy` from the keypair in .env.
// Commit changes to this file — public keys are the trust root, not secret.
// If you rotate the keypair in .env, re-run the deploy task and commit the
// updated values here so existing core binaries can verify new manifests.

export const MANIFEST_PUBLIC_KEY_B64 =
  "KghrHOIqu76Hpl/xX8RHUuDA2n1NGCOj9gD1Jrn5H+M=";
export const CORE_PUBLIC_KEY_B64 =
  "KghrHOIqu76Hpl/xX8RHUuDA2n1NGCOj9gD1Jrn5H+M=";
