// Dev tool: resolve the sha256 of every downloadable file in the
// `@tomat/model-catalog` source and write it to `src/hashes.generated.ts`.
// `buildCatalogPayload` stamps these onto the catalog so a model download
// verifies its bytes against the SIGNED catalog instead of trusting HF's
// `x-linked-etag` (which a proxy can strip or a non-HF mirror omit).
//
// For git-LFS objects (every GGUF + the large ONNX weights) the sha256 is the
// LFS `oid` from the HF tree API: authoritative, no download. The handful of
// small non-LFS files (tokens.txt, configs) have only a git-blob sha1 in the
// tree, so those are fetched and hashed directly.
//
// Usage: deno run -A scripts/catalog/gather-hashes.ts

import { createHash } from "node:crypto";
import {
  FAMILIES,
  STT_CATALOG,
  TTS_CATALOG,
} from "../../packages/tomat-model-catalog/src/index.ts";

const HF = "https://huggingface.co";

function parseSpec(spec: string): { repo: string; branch: string; file: string } | null {
  const m = spec.match(/^@([^/]+)\/([^/]+)\/([^/]+)\/(.+)$/);
  if (!m) return null;
  const [, user, repo, branch, file] = m;
  return { repo: `${user}/${repo}`, branch, file };
}

/** Every distinct downloadable modelSpec across the catalog source. */
function allSpecs(): string[] {
  const specs = new Set<string>();
  for (const fam of FAMILIES) {
    for (const model of fam.models) {
      for (const v of model.variants) {
        if (v.mmprojSpec) specs.add(v.mmprojSpec);
        for (const q of v.quants) specs.add(q.modelSpec);
      }
    }
  }
  for (const m of STT_CATALOG.models) {
    for (const q of m.quants) for (const f of q.files) specs.add(f.modelSpec);
  }
  for (const m of TTS_CATALOG.models) {
    for (const q of m.quants) for (const f of q.files) specs.add(f.modelSpec);
  }
  return [...specs].sort();
}

// Per-repo LFS tree (path -> oid), fetched once per repo+branch.
const treeCache = new Map<string, Map<string, string>>();
async function treeOids(repo: string, branch: string): Promise<Map<string, string>> {
  const key = `${repo}@${branch}`;
  const cached = treeCache.get(key);
  if (cached) return cached;
  const res = await fetch(`${HF}/api/models/${repo}/tree/${branch}?recursive=true`);
  if (!res.ok) throw new Error(`tree ${repo}@${branch}: HTTP ${res.status}`);
  const json = (await res.json()) as Array<{ path: string; lfs?: { oid?: string } }>;
  const map = new Map<string, string>();
  for (const e of json) {
    if (e.lfs?.oid && /^[0-9a-f]{64}$/.test(e.lfs.oid)) {
      map.set(e.path, e.lfs.oid);
    }
  }
  treeCache.set(key, map);
  return map;
}

async function downloadSha256(repo: string, branch: string, file: string): Promise<string> {
  const url = `${HF}/${repo}/resolve/${branch}/${file}`;
  const res = await fetch(url);
  if (!res.ok || !res.body) {
    throw new Error(`download ${url}: HTTP ${res.status}`);
  }
  const hash = createHash("sha256");
  for await (const chunk of res.body) hash.update(chunk);
  return hash.digest("hex");
}

const out: Record<string, string> = {};
const missing: string[] = [];
for (const spec of allSpecs()) {
  const p = parseSpec(spec);
  if (!p) {
    console.error(`SKIP (unparseable) ${spec}`);
    missing.push(spec);
    continue;
  }
  try {
    const oids = await treeOids(p.repo, p.branch);
    const sha = oids.get(p.file) ?? (await downloadSha256(p.repo, p.branch, p.file));
    out[spec] = sha.toLowerCase();
    console.error(`ok   ${spec} -> ${sha.slice(0, 12)}`);
  } catch (err) {
    console.error(`MISS ${spec}: ${err instanceof Error ? err.message : String(err)}`);
    missing.push(spec);
  }
}

const sorted = Object.keys(out).sort();
const entries = sorted.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`).join("\n");
const content = `// GENERATED by scripts/catalog/gather-hashes.ts. Do not edit by hand.
//
// modelSpec -> sha256 for every downloadable catalog file, gathered from
// HuggingFace (git-LFS oid for weights; computed for small non-LFS files).
// buildCatalogPayload stamps these onto the catalog so model downloads verify
// against the signed catalog rather than HF's x-linked-etag.

export const FILE_HASHES: Record<string, string> = {
${entries}
};
`;
const dest = new URL("../../packages/tomat-model-catalog/src/hashes.generated.ts", import.meta.url);
await Deno.writeTextFile(dest, content);
console.error(`\nwrote ${sorted.length} hashes to hashes.generated.ts; ${missing.length} missing`);
if (missing.length > 0) {
  console.error(`missing:\n${missing.map((s) => `  ${s}`).join("\n")}`);
}
