// Binary-manifest fetch + signature verification.
//
// Manifest schema (see plan §8):
//   {
//     "schemaVersion": 1,
//     "binaries": { <kind>: { version, platforms: { <triple>: { url, sha256 } } } },
//     "signature": base64-Ed25519(JSON.stringify(manifest.binaries))
//   }
//
// The Ed25519 public key is baked into the running core binary (see
// data/signing-keys.json; regenerated by `deno task release:core`).
//
// On first fetch we cache the parsed + verified manifest at
// ~/.tomat/core/cache/binaries-manifest.json so subsequent boots can install
// missing binaries offline (assuming the operator's prior fetch was good).

import { verifyAsync } from "@noble/ed25519";
import { canonicalize, decodeBase64, errMessage } from "@tomat/shared";
import { join } from "@std/path";
import { binaryManifestUrl } from "../config.ts";
import { channel, paths } from "../paths.ts";
import { AppError } from "../shared/errors.ts";
import signingKeys from "../../data/signing-keys.json" with { type: "json" };
import type { BinaryKind, BinaryManifest, BinaryManifestEntry } from "@tomat/shared";
import { BINARY_KINDS, UPSTREAM_BINARIES } from "@tomat/shared";

const SIG_ALGO_LABEL = "ed25519-base64";

export interface FetchOptions {
  // Force a network fetch even if the cached manifest is fresh.
  force?: boolean;
  // If set, an AbortSignal propagated into fetch().
  signal?: AbortSignal;
}

export async function loadBinaryManifest(opts: FetchOptions = {}): Promise<BinaryManifest> {
  // Dev runs from source, so there is no published manifests/dev/binaries.json
  // to fetch and sign-verify. The resolver config embedded in this build IS the
  // trust anchor, so build resolver entries in-code: a dev core then pulls the
  // LATEST upstream sidecar release at install/update time, exactly like beta.
  if (channel() === "dev") return devManifest();
  const cached = await readCachedManifest();
  if (cached && !opts.force) return cached;
  const fetched = await fetchAndVerify(opts.signal);
  await writeCachedManifest(fetched);
  return fetched;
}

/** In-code resolver manifest for the dev channel (no network, no signature:
 *  the config is part of this from-source build). Same shape a beta release
 *  would publish, so the runtime resolver path is identical. */
function devManifest(): BinaryManifest {
  const binaries = {} as Record<BinaryKind, BinaryManifestEntry>;
  for (const kind of BINARY_KINDS) {
    binaries[kind] = { resolver: UPSTREAM_BINARIES[kind] };
  }
  return { schemaVersion: 1, binaries, signature: "" };
}

async function fetchAndVerify(signal?: AbortSignal): Promise<BinaryManifest> {
  let res: Response;
  try {
    res = await fetch(binaryManifestUrl(), { signal });
  } catch (err) {
    throw new AppError(
      "manifest_fetch_failed",
      `failed to fetch binary manifest: ${errMessage(err)}`,
    );
  }
  if (!res.ok) {
    throw new AppError(
      "manifest_fetch_failed",
      `binary manifest HTTP ${res.status} ${res.statusText}`,
    );
  }
  const raw = await res.text();
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new AppError("manifest_fetch_failed", `invalid manifest JSON: ${errMessage(err)}`);
  }
  assertManifestShape(parsed);
  await verifyManifestSignature(parsed);
  return parsed;
}

export function assertManifestShape(value: unknown): asserts value is BinaryManifest {
  if (!value || typeof value !== "object") {
    throw new AppError("manifest_fetch_failed", "manifest is not an object");
  }
  const o = value as Record<string, unknown>;
  if (o.schemaVersion !== 1) {
    throw new AppError(
      "manifest_fetch_failed",
      `unsupported schemaVersion: ${String(o.schemaVersion)}`,
    );
  }
  if (!o.binaries || typeof o.binaries !== "object") {
    throw new AppError("manifest_fetch_failed", "manifest missing binaries");
  }
  if (typeof o.signature !== "string" || o.signature.length === 0) {
    throw new AppError("manifest_fetch_failed", "manifest missing signature");
  }
}

/** Verify a binaries-manifest signature: Ed25519 over canonicalize(binaries).
 *  Key-injectable + pure so it's unit-testable with a throwaway keypair; the
 *  production path passes the embedded signing key. Exported for testing. */
export async function verifyBinariesSignature(
  binaries: unknown,
  signatureB64: string,
  publicKey: Uint8Array,
): Promise<boolean> {
  const sig = decodeBase64(signatureB64);
  const message = new TextEncoder().encode(canonicalize(binaries));
  return await verifyAsync(sig, message, publicKey);
}

async function verifyManifestSignature(m: BinaryManifest): Promise<void> {
  const pk = decodeBase64(signingKeys.publicKey);
  const ok = await verifyBinariesSignature(m.binaries, m.signature, pk);
  if (!ok) {
    throw new AppError(
      "signature_invalid",
      `manifest signature (${SIG_ALGO_LABEL}) verification failed`,
    );
  }
}

async function readCachedManifest(): Promise<BinaryManifest | null> {
  const cachePath = manifestCachePath();
  try {
    const text = await Deno.readTextFile(cachePath);
    const parsed = JSON.parse(text);
    assertManifestShape(parsed);
    // Re-verify on every read; cache is a perf optimization, not a trust
    // anchor.
    await verifyManifestSignature(parsed);
    return parsed;
  } catch {
    return null;
  }
}

async function writeCachedManifest(m: BinaryManifest): Promise<void> {
  const cachePath = manifestCachePath();
  await Deno.mkdir(paths().cacheDir, { recursive: true });
  const tmp = cachePath + ".tmp";
  await Deno.writeTextFile(tmp, JSON.stringify(m));
  await Deno.rename(tmp, cachePath);
}

function manifestCachePath(): string {
  return join(paths().cacheDir, "binaries-manifest.json");
}
