// Binary-manifest fetch + signature verification.
//
// Manifest schema (see plan §8):
//   {
//     "schemaVersion": 1,
//     "binaries": { <kind>: { version, platforms: { <triple>: { url, sha256 } } } },
//     "signature": base64-Ed25519(JSON.stringify(manifest.binaries))
//   }
//
// The Ed25519 public key is baked into the running core binary (see
// data/signing-keys.json; regenerated by `deno task release:core`).
//
// On first fetch we cache the parsed + verified manifest at
// ~/.tomat/core/cache/binaries-manifest.json so subsequent boots can install
// missing binaries offline (assuming the operator's prior fetch was good).

import { verifyAsync } from "@noble/ed25519";
import { errMessage } from "@tomat/shared";
import { join } from "@std/path";
import { binaryManifestUrl } from "../config.ts";
import { paths } from "../paths.ts";
import { AppError } from "../shared/errors.ts";
import signingKeys from "../../data/signing-keys.json" with { type: "json" };
import type { BinaryManifest } from "@tomat/shared";

const SIG_ALGO_LABEL = "ed25519-base64";

export interface FetchOptions {
  // Force a network fetch even if the cached manifest is fresh.
  force?: boolean;
  // If set, an AbortSignal propagated into fetch().
  signal?: AbortSignal;
}

export async function loadBinaryManifest(
  opts: FetchOptions = {},
): Promise<BinaryManifest> {
  const cached = await readCachedManifest();
  if (cached && !opts.force) return cached;
  const fetched = await fetchAndVerify(opts.signal);
  await writeCachedManifest(fetched);
  return fetched;
}

async function fetchAndVerify(signal?: AbortSignal): Promise<BinaryManifest> {
  let res: Response;
  try {
    res = await fetch(binaryManifestUrl(), { signal });
  } catch (err) {
    throw new AppError(
      "manifest_fetch_failed",
      `failed to fetch binary manifest: ${errMessage(err)}`,
    );
  }
  if (!res.ok) {
    throw new AppError(
      "manifest_fetch_failed",
      `binary manifest HTTP ${res.status} ${res.statusText}`,
    );
  }
  const raw = await res.text();
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new AppError(
      "manifest_fetch_failed",
      `invalid manifest JSON: ${errMessage(err)}`,
    );
  }
  assertManifestShape(parsed);
  await verifyManifestSignature(parsed);
  return parsed;
}

function assertManifestShape(value: unknown): asserts value is BinaryManifest {
  if (!value || typeof value !== "object") {
    throw new AppError("manifest_fetch_failed", "manifest is not an object");
  }
  const o = value as Record<string, unknown>;
  if (o.schemaVersion !== 1) {
    throw new AppError(
      "manifest_fetch_failed",
      `unsupported schemaVersion: ${String(o.schemaVersion)}`,
    );
  }
  if (!o.binaries || typeof o.binaries !== "object") {
    throw new AppError("manifest_fetch_failed", "manifest missing binaries");
  }
  if (typeof o.signature !== "string" || o.signature.length === 0) {
    throw new AppError("manifest_fetch_failed", "manifest missing signature");
  }
}

async function verifyManifestSignature(m: BinaryManifest): Promise<void> {
  const pk = decodeBase64(signingKeys.publicKey);
  const sig = decodeBase64(m.signature);
  const message = new TextEncoder().encode(canonicalize(m.binaries));
  const ok = await verifyAsync(sig, message, pk);
  if (!ok) {
    throw new AppError(
      "signature_invalid",
      `manifest signature (${SIG_ALGO_LABEL}) verification failed`,
    );
  }
}

// Stable JSON serialization: sorted keys, no whitespace. Both the signing
// tool and this verifier must agree on this representation.
function canonicalize(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return "[" + value.map(canonicalize).join(",") + "]";
  }
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return "{" +
    keys.map((k) => JSON.stringify(k) + ":" + canonicalize(obj[k])).join(",") +
    "}";
}

function decodeBase64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function readCachedManifest(): Promise<BinaryManifest | null> {
  const cachePath = manifestCachePath();
  try {
    const text = await Deno.readTextFile(cachePath);
    const parsed = JSON.parse(text);
    assertManifestShape(parsed);
    // Re-verify on every read; cache is a perf optimization, not a trust
    // anchor.
    await verifyManifestSignature(parsed);
    return parsed;
  } catch {
    return null;
  }
}

async function writeCachedManifest(m: BinaryManifest): Promise<void> {
  const cachePath = manifestCachePath();
  await Deno.mkdir(paths().cacheDir, { recursive: true });
  const tmp = cachePath + ".tmp";
  await Deno.writeTextFile(tmp, JSON.stringify(m));
  await Deno.rename(tmp, cachePath);
}

function manifestCachePath(): string {
  return join(paths().cacheDir, "binaries-manifest.json");
}
