// Builds the Tauri client for iOS for the requested channel.
//
// Channel handling mirrors build-android.ts:
//   - The channel is written to the Tauri crate's `channel` file, which build.rs
//     bakes into the shipped app via `option_env!("TOMAT_CHANNEL")` in channel.rs
//     (its runtime default -> the channel's app-data dir, tomat-client-<channel>
//     secret store). A file rather than the build env because Xcode's script
//     phase does not forward TOMAT_CHANNEL to the cargo compile.
//   - The on-device label, per-channel bundle id, and version are written into a
//     build-time xcconfig (gen/apple/tauri-channel.xcconfig, referenced by
//     project.yml via configFiles), the iOS analogue of android's autogenerated
//     tauri.properties + applicationIdSuffix: TOMAT_DISPLAY_NAME gives dev/latest
//     a "tomat (latest)" / "tomat (dev)" label, TOMAT_BUNDLE_ID_SUFFIX gives them
//     a distinct au.tomat.ing.<channel> bundle id for side-by-side install, and
//     MARKETING_VERSION comes from tauri.conf.json so the version never drifts.
//     We do NOT override the Tauri `identifier`: it is fixed into the Xcode target
//     references at `tauri ios init`, so overriding it makes xcodebuild look for a
//     target that does not exist (same reasoning as Android).
//
// Distribution is App Store only (iOS cannot sideload a signed .ipa the way
// Android installs an APK), so there is no self-hosted manifest and no updater
// endpoint. When Apple signing is configured this builds a signed .ipa for App
// Store Connect; without it, it falls back to an unsigned Simulator build so
// local iteration still works without an Apple Developer account. iOS is
// macOS-only; off a mac the task self-skips.

import { parseArgs } from "@std/cli/parse-args";
import { fromFileUrl, join } from "@std/path";
import { iosToolchainReady } from "./release/apple-toolchain.ts";

const ROOT = fromFileUrl(new URL("..", import.meta.url));

const args = parseArgs(Deno.args, {
  string: ["channel"],
  default: { channel: "stable" },
});

const channel = args.channel;
if (!["stable", "dev", "latest"].includes(channel)) {
  console.error(`invalid --channel: ${channel} (expected stable, dev, or latest)`);
  Deno.exit(1);
}

if (!iosToolchainReady()) {
  console.error(
    "iOS builds require macOS with Xcode and the aarch64-apple-ios rust target; " +
      "skipping the iOS build on this host.",
  );
  Deno.exit(0);
}

// A real signing identity (Team ID + a certificate) is needed for a device/App
// Store .ipa. Without it we can still produce an unsigned Simulator build.
const team = Deno.env.get("APPLE_TEAM_ID");
const hasSigning =
  !!team && (!!Deno.env.get("APPLE_SIGNING_IDENTITY") || !!Deno.env.get("APPLE_CERTIFICATE"));

// Materialize the build-time xcconfig that project.yml references (configFiles).
// This is the iOS analogue of android's autogenerated tauri.properties +
// applicationIdSuffix, regenerated on every build:
//   - MARKETING_VERSION / CURRENT_PROJECT_VERSION come from tauri.conf.json's
//     `version`, so the iOS version never drifts from the Tauri config.
//   - TOMAT_BUNDLE_ID_SUFFIX gives dev/latest a distinct au.tomat.ing.<channel>
//     bundle id so they install alongside stable (empty for stable).
//   - TOMAT_DISPLAY_NAME is the on-device label ("tomat" / "tomat (latest)" /
//     "tomat (dev)"), matching the desktop naming. PRODUCT_NAME stays "tomat".
const tauriConf = JSON.parse(
  await Deno.readTextFile(join(ROOT, "packages/tomat-client/src/tauri/tauri.conf.json")),
) as { version: string };
const bundleIdSuffix = channel === "stable" ? "" : `.${channel}`;
const displayName = channel === "stable" ? "tomat" : `tomat (${channel})`;
// Bake the channel for channel.rs (via build.rs). Xcode's script phase does not
// forward TOMAT_CHANNEL to the cargo compile, so the on-disk file is the
// deterministic source (see build.rs).
await Deno.writeTextFile(join(ROOT, "packages/tomat-client/src/tauri/channel"), channel);
await Deno.writeTextFile(
  join(ROOT, "packages/tomat-client/src/tauri/gen/apple/tauri-channel.xcconfig"),
  `// AUTOGENERATED by scripts/build-ios.ts from tauri.conf.json + TOMAT_CHANNEL.
// DO NOT EDIT. Regenerated every build so the iOS version tracks the Tauri config
// and the per-channel identity matches the desktop/android channels.
MARKETING_VERSION = ${tauriConf.version}
CURRENT_PROJECT_VERSION = ${tauriConf.version}
TOMAT_BUNDLE_ID_SUFFIX = ${bundleIdSuffix}
TOMAT_DISPLAY_NAME = ${displayName}
`,
);

const tauriArgs = ["run", "-A", "npm:@tauri-apps/cli@^2", "ios", "build"];
if (hasSigning) {
  // A signed archive exported for App Store Connect / TestFlight.
  tauriArgs.push("--export-method", "app-store-connect");
} else {
  // No Apple signing configured: build for the Simulator so the task still
  // produces a runnable artifact without an Apple Developer account.
  console.error(
    "APPLE_TEAM_ID / signing not set; building an unsigned Simulator app " +
      "(a signed .ipa needs an Apple Developer account).",
  );
  tauriArgs.push("--target", "aarch64-sim");
}

const cmd = new Deno.Command("deno", {
  args: tauriArgs,
  cwd: join(ROOT, "packages/tomat-client"),
  env: {
    ...Deno.env.toObject(),
    TOMAT_CHANNEL: channel,
    ...(team ? { APPLE_DEVELOPMENT_TEAM: team } : {}),
  },
  stdout: "inherit",
  stderr: "inherit",
});
const { code } = await cmd.output();
Deno.exit(code);
